# Generated by Django 4.0.3 on 2022-03-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_form_consultation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='user',
            new_name='patient',
        ),
    ]
