# Generated by Django 4.0.3 on 2022-03-14 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('residence', models.CharField(max_length=120)),
                ('hc_medical_advisor', models.CharField(max_length=120)),
                ('referral_medical_advisor', models.CharField(max_length=120)),
                ('consultation_number', models.IntegerField()),
                ('consulation_fees', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
