# Generated by Django 4.0.3 on 2022-03-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='consulation_fees',
        ),
        migrations.RemoveField(
            model_name='form',
            name='consultation_number',
        ),
        migrations.RemoveField(
            model_name='form',
            name='hc_medical_advisor',
        ),
        migrations.RemoveField(
            model_name='form',
            name='referral_medical_advisor',
        ),
        migrations.RemoveField(
            model_name='form',
            name='residence',
        ),
    ]
