# Generated by Django 4.0.3 on 2022-03-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_test_alter_medicine_price_formtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
